---
# tasks file for rundeck

- include: "{{ ansible_os_family | lower }}_repository.yml"

- name: Install from repository
  package:
    name: rundeck
    state: present

- include: debian_systemd.yml
  when: ansible_os_family == 'Debian'

- name: Write rundeck config
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - "{{ rundeck_configs }}"
  notify:
    - restart rundeck

- name: Start rundeck
  service:
    name: rundeckd
    enabled: yes
    state: started

- name: Download rundeck plugins
  get_url:
    dest: "/var/lib/rundeck/libext/{{ item.split('/') | last }}"
    url: "{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - "{{ rundeck_plugins }}"
  notify:
    - restart rundeck
