---
version: 2
jobs:
  build:

    machine:
      enabled: true

    working_directory: ~/rundeck

    steps:
      - checkout:
          path: ~/rundeck

      - run:
          name: "update"
          command: |
            sudo apt-get update

      - run:
          name: "install tools"
          command: >
            sudo apt-get install -yq
            apt-transport-https
            build-essential curl git
            software-properties-common

      - run:
          name: "install nodejs, npm & semantic-release"
          command: |
            sudo apt-get install -yq nodejs npm
            npm install -g semantic-release@13

      # - run:
      #     name: "install ruby & fpm"
      #     command: |
      #       sudo apt-get install -yq ruby-dev ruby libffi-dev
      #       gem install fpm --no-ri --no-rdoc

      - run:
          name: "install python & tools"
          command: |
            sudo apt-get install -yq python python-pip
            pip install --upgrade pip
            pip install virtualenv

      - restore_cache:
          keys:
            - v4-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: "Install python dependencies"
          command: |
            virtualenv ~/.venv
            source ~/.venv/bin/activate
            pip install -r requirements.txt
            deactivate

      - save_cache:
          paths:
            - ~/.venv
            - ~/.cache/pip
          key: v4-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: "run tests"
          command: |
            source ~/.venv/bin/activate
            molecule test
