---
# handlers file for rundeck

- name: start rundeck
  service:
    name: rundeckd
    state: started

- name: stop rundeck
  service:
    name: rundeckd
    state: stopped

- name: restart rundeck
  service:
    name: rundeckd
    state: restarted

- name: reload rundeck
  service:
    name: rundeckd
    state: reloaded